/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class bai3 extends javax.swing.JFrame {
    List<Nhanvien> listnv = new ArrayList<>();
    /**
     * Creates new form bai3
     */
    public bai3() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();
        lblquanlynhanvien = new javax.swing.JLabel();
        lblhoten = new javax.swing.JLabel();
        lbluong = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtluong = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btndoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Lương"
            }
        ));
        jScrollPane1.setViewportView(tblbang);

        lblquanlynhanvien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblquanlynhanvien.setForeground(new java.awt.Color(204, 51, 0));
        lblquanlynhanvien.setText("QUẢN LÝ NHÂN VIÊN");

        lblhoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblhoten.setText("Họ và tên");

        lbluong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbluong.setText("Lương");

        btnthem.setText("THÊM");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnluu.setText("LƯU");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btndoc.setText("ĐỌC");
        btndoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhoten)
                    .addComponent(lbluong))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnluu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndoc))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblquanlynhanvien)
                        .addComponent(txthoten)
                        .addComponent(txtluong, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblquanlynhanvien)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhoten)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluong)
                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnluu)
                    .addComponent(btndoc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        try {
            them();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        try {
            // TODO add your handling code here:

            Xfile.ghidoituong("Z:/HocCode2/Java2/FileOutput/outputFile.txt", listnv);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnluuActionPerformed

    private void btndocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocActionPerformed
        try {
            // TODO add your handling code here:
            listnv = (List<Nhanvien>) Xfile.docdoituong("Z:/HocCode2/Java2/FileOutput/outputFile.txt");
        } catch (IOException ex) {        
        } catch (ClassNotFoundException ex) {
        }
        filltoTable();

    }//GEN-LAST:event_btndocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndoc;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnthem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblquanlynhanvien;
    private javax.swing.JLabel lbluong;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtluong;
    // End of variables declaration//GEN-END:variables

    void them() {
            Nhanvien nv1 = new Nhanvien();

            nv1.setHoten(txthoten.getText());
            nv1.setLuong(Double.valueOf(txtluong.getText()));
            listnv.add(nv1);
            filltoTable();
        try {
            Xfile.ghidoituong("Z:/HocCode2/Java2/FileOutput/outputFile.txt", listnv);
        } catch (IOException ex) {
            Logger.getLogger(bai3.class.getName()).log(Level.SEVERE, null, ex);
        }
    };
    void filltoTable() {
            DefaultTableModel cotnv = (DefaultTableModel) tblbang.getModel();
            cotnv.setRowCount(0);
            for (Nhanvien nv1 : listnv) {
                Object[] rowObjects = new Object[]{nv1.getHoten(), nv1.getLuong()};
                cotnv.addRow(rowObjects);
            }
        }

}

